name: Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Update apt
    #   run: |
    #     sudo apt update
    #     sudo apt upgrade
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with: 
        distribution: 'adopt'
        java-version: '17' 
    
    - name: Download and setup Minecraft server
      run: |
        wget https://piston-data.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b7b4fc76e594d/server.jar
        java -Xmx1024M -Xms1024M -jar minecraft_server.1.20.4.jar nogui
      
    - name: Set Eula and Prorpieties
      run: |
        echo eula=true > eula.txt
        echo server-ip=26.175.173.254 >> server.properties
        echo server-port=25565 >> server.properties

    - name: Start Server
      run:  java -Xmx1024M -Xms1024M -jar minecraft_server.1.20.4.jar nogui
