name: Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Update apt
    #   run: |
    #     sudo apt update
    #     sudo apt upgrade
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with: 
        distribution: 'adopt'
        java-version: '17' 
    
    - name: Download and setup Minecraft server
      run: |
        wget https://api.papermc.io/v2/projects/paper/versions/1.20.4/builds/454/downloads/paper-1.20.4-454.jar -O server.jar
        echo "server-ip=26.175.173.254"
        java -Xmx1024M -Xms1024M -jar server.jar nogui
        sleep infinity
