name: Minecraft Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Update apt
    #   run: |
    #     sudo apt update
    #     sudo apt upgrade
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with: 
        distribution: 'adopt'
        java-version: '17' 
    
    - name: Download and setup Minecraft server
      run: |
        wget https://piston-data.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b7b4fc76e594d/server.jar
        java -Xmx4G -Xms1024M -jar server.jar nogui

        - name: Stop Server
        run: |
          # Find the PID of the server process
          PID=$(pgrep -f "java -jar your_server.jar")
  
          # Check if the PID is found
          if [ -n "$PID" ]; then
            echo "Stopping server..."
            kill "$PID"
          else
            echo "Server process not found."
          fi
          
    - name: Set Eula and Prorpieties
      run: |
        echo  eula=true > eula.txt
        echo  > server.properties
        echo  online-mode=true > server.properties
        echo  op-permission-level=4 > server.properties
        echo  player-idle-timeout=0 > server.properties
        echo  prevent-proxy-connections=false > server.properties
        echo  pvp=true > server.properties
        echo  query.port=25565 > server.properties
        echo  allow-flight=false > server.properties
        echo  allow-nether=true  > server.properties
        echo  broadcast-console-to-ops=true > server.properties
        echo  broadcast-rcon-to-ops=true  > server.properties
        echo  difficulty=easy > server.properties
        echo  enable-command-block=true > server.properties
        echo  enable-jmx-monitoring=false > server.properties
        echo  enable-query=false > server.properties
        echo  enable-rcon=false > server.properties
        echo  enable-status=true > server.properties
        echo  enforce-secure-profile=true > server.properties
        echo  enforce-whitelist=false > server.properties
        echo  entity-broadcast-range-percentage=100 > server.properties
        echo  force-gamemode=false > server.properties
        echo  function-permission-level=2 > server.properties
        echo  gamemode=creative > server.properties
        echo  generate-structures=true > server.properties
        echo  generator-settings={} > server.properties
        echo  hardcore=false > server.properties
        echo  hide-online-players=false > server.properties
        echo  initial-disabled-packs= > server.properties
        echo  initial-enabled-packs=vanilla > server.properties
        echo  level-name=banana > server.properties
        echo  level-seed= > server.properties
        echo  level-type=minecraft\:normal > server.properties
        echo  log-ips=true > server.properties
        echo  max-chained-neighbor-updates=1000000 > server.properties
        echo  max-players=20 > server.properties
        echo  max-tick-time=60000 > server.properties
        echo  max-world-size=29999984 > server.properties
        echo  motd=Git Server > server.properties
        echo  network-compression-threshold=256 > server.properties
        echo  rate-limit=0 > server.properties
        echo  rcon.password= > server.properties
        echo  rcon.port=25575 > server.properties
        echo  require-resource-pack=false > server.properties
        echo  resource-pack= > server.properties
        echo  resource-pack-id= > server.properties
        echo  resource-pack-prompt= > server.properties
        echo  resource-pack-sha1= > server.properties
        echo  server-ip=26.175.173.254 > server.properties
        echo  server-port=25565 > server.properties
        echo  simulation-distance=10 > server.properties
        echo  spawn-animals=true > server.properties
        echo  spawn-monsters=true > server.properties
        echo  spawn-npcs=true > server.properties
        echo  spawn-protection=16 > server.properties
        echo  sync-chunk-writes=true > server.properties
        echo  text-filtering-config= > server.properties
        echo  use-native-transport=true > server.properties
        echo  view-distance=10 > server.properties
        echo  white-list=false > server.properties

    - name: Start Server
      run:  |
        java -Xmx4G -Xms1024M -jar server.jar nogui
